spring:
  profiles:
    active: dev
  # 应用配置
  application:
    group: MACULA
    name: macula-samples-steam-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${macula.rocketmq.url}
        bindings:
          input1:
            consumer:
              orderly: true
          input2:
            consumer:
              orderly: false
              tags: tagStr
          input3:
            consumer:
              tags: tagObj
      bindings:
        input1:
          destination: test-topic
          content-type: text/plain
          group: test-group1
        input2:
          destination: test-topic
          content-type: text/plain
          group: test-group2
          consumer:
            concurrency: 20
            maxAttempts: 1
        input3:
          destination: test-topic
          content-type: application/json
          group: test-group3
          consumer:
            concurrency: 20
        input4:
          destination: TransactionTopic
          content-type: text/plain
          group: transction-group
          consumer:
            concurrency: 5
        input5:
          destination: pull-topic
          content-type: text/plain
          group: pull-topic-group
server:
  port: 28082

logging:
  level:
    com.alibaba.cloud.stream.binder.rocketmq: DEBUG

macula:
  datasource:
    druid:
      - name: macula-samples
        ## JDBC配置
        url: ${macula.datasource.macula-samples.url}
        username: ${macula.datasource.macula-samples.username}
        password: ${macula.datasource.macula-samples.password}
        ## 连接池配置
        max-active: 100
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select '1'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
        ## 过滤器配置
        filters: stat,wall
  jpa:
    repositories:
      - name: macula-samples
        entity-packages: org.macula.samples
        repository-packages: org.macula.samples
        service-package: org.macula.samples

---
spring:
  profiles: dev

macula:
  datasource:
    macula-samples:
      url: jdbc:mysql://127.0.0.1:3306/macula-samples?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: mysql
  rocketmq:
    url: 127.0.0.1:9876